### ISSUE TITLE
Groundpounding while holding sprint, forward, and jump delays the groundpound

### ISSUE THREAD

**Issue by Oliver-makes-code** [Ignoramuses/bing-bing-wahoo#3] opened 2021-11-24 16:35 UTC
When holding sprint, forward, and jump, it causes the end of the groundpound animation to be delayed until all of the keys are released.

**Comment by TropheusJ** [comment] 2021-11-25 05:59
cannot reproduce, can you elaborate?

**Comment by TropheusJ** [comment] 2022-11-19 07:26
I think it's safe to close this after a year of nothing

**Closed as completed by TropheusJ** 2022-11-19 07:26 UTC
